# This is a minimal essential configuration to have you runner up and running
apiVersion: gitlab.k8s.alekc.dev/v1alpha1
kind: Runner
metadata:
  name: runner-sample
spec:
  registration_config:
    token: "rYwg6EogqxSuvsFCVvAT"
    tag_list:
      - test-gitlab-runner
