apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: metrics-reader
  labels:
  {{- include "gitlab-runner-operator.labels" . | nindent 4 }}
rules:
- nonResourceURLs: ["/metrics"]
  verbs: ["get"]
