# permissions for end users to edit runners.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: runner-editor-role
  labels:
    {{- include "gitlab-runner-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - gitlab.k8s.alekc.dev
  resources:
  - runners
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - gitlab.k8s.alekc.dev
  resources:
  - runners/status
  verbs:
  - get
